-- Create the tracker_data table for storing twins tracker data
CREATE TABLE IF NOT EXISTS tracker_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id TEXT UNIQUE NOT NULL,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create an index on device_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_tracker_data_device_id ON tracker_data(device_id);

-- Enable Row Level Security (optional, but recommended)
ALTER TABLE tracker_data ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows all operations (for simplicity with publishable key)
-- In production, you'd want more restrictive policies with proper auth
CREATE POLICY "Allow all operations" ON tracker_data
  FOR ALL
  USING (true)
  WITH CHECK (true);
